### ISSUE TITLE
Django REST Serializers

### ISSUE THREAD

**Issue by elcolie** [NorakGithub/django-model-controller#1]
I request Django REST serializers support in the next release

**Comment by NorakGithub** [comment]
Agree 👍

**Comment by elcolie** [comment]
Hi. It is 8 months by now do you have any changes?

**Comment by NorakGithub** [comment]
Sorry I forgot about that, let me find time after done will report back to you.

**Comment by elcolie** [comment]
Okay

**Comment by NorakGithub** [comment]
`ModelControllerSerializer` has been added
