### ISSUE TITLE
Update NullBooleanField > BooleanField

### ISSUE THREAD

**Issue by ratthananp** [NorakGithub/django-model-controller#4]
For support Django 4.0 😭😭

![Screen Shot 2563-08-20 at 19 04 33](https://user-images.githubusercontent.com/46515647/90768067-6287ab00-e318-11ea-8c09-97ffdfd4a50a.png)

**Comment by NorakGithub** [comment]
@ratthananp This was fix in v0.4.0 na krub
https://github.com/NorakGithub/django-model-controller/commit/d782bfb47f861005b80e1ecbe07aa85b31d7cf0b
